print("From Main Branch")
print("there must be conflict")
print("From Modify by feature 1")
print("dummy")
print("from feature one")
print("another main")
print("another feature one")
print("hiii feature one")
print("This is a second one")